/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * T_x_to_z.c
 *
 * Code generation for function 'T_x_to_z'
 *
 */

/* Include files */
#include "T_x_to_z.h"
#include "mwmathutil.h"
#include "rt_nonfinite.h"

/* Function Definitions */
void T_x_to_z(const emlrtStack *sp, const real_T in1[8], real_T z[8])
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t15;
  (void)sp;

  /* T_X_TO_Z */
  /*     Z = T_X_TO_Z(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
  /*     07-Jun-2020 14:23:39 */
  t2 = muDoubleScalarCos(in1[3]);
  t3 = muDoubleScalarSin(in1[3]);
  t4 = t2 * t2;
  t5 = t3 * t3;
  t15 = 1.0 / (((((t3 * 1.6624316354668391E-14 - t3 * t4 *
                   4.8224626801869287E-15) + -(t4 * 2.554188920360585E-13)) + t5
                 * 8.0736743342654317E-13) + -(t4 * t5 * 2.342050785026386E-13))
               + 8.8049711231808578E-13);
  z[0] = in1[0];
  z[1] = in1[1];
  z[2] = in1[2];
  z[3] = in1[3];
  z[4] = in1[4];
  z[5] = in1[5] + in1[7] * (t15 * ((t2 * 1.133180532546843E-12 + t2 * t3 *
    2.1395131677847961E-14) + t2 * t5 * 1.039064234705584E-12) * 0.02975 + t15 *
    ((t3 * 1.0724748384E-10 + t5 * 5.20852249933514E-9) + 5.6802997374374863E-9)
    * 4.4911946750946972E-5) * (t4 * 4.49657419225E-5 - 0.0001550089173138068) /
    (t2 * 0.0001994930875 + 9.08773621875E-5);
  z[6] = in1[6];
  z[7] = in1[7];
}

/* End of code generation (T_x_to_z.c) */
