function H_x = measurement_jacobian_function(in1,in2,in3,dt)
%MEASUREMENT_JACOBIAN_FUNCTION
%    H_X = MEASUREMENT_JACOBIAN_FUNCTION(IN1,IN2,IN3,DT)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    02-Aug-2019 13:28:46

b_q = in1(5,:);
q = in2(2,:);
r = in2(3,:);
theta_p = in1(1,:);
t2 = sin(theta_p);
t3 = cos(theta_p);
t4 = b_q-q;
t5 = dt.*3.361344537815126e1;
t6 = r.*t2.*(3.6e1./1.7e1);
t7 = t3.*t4.*(3.6e1./1.7e1);
t8 = t6+t7;
t9 = r.*t2.*(6.0e1./1.7e1);
t10 = t3.*t4.*(6.0e1./1.7e1);
t11 = t9+t10;
H_x = reshape([-dt.*t11,-dt.*t8,dt.*t8,dt.*t11,t3,-t2,-r.*t3+t2.*t4,dt.*(-3.361344537815126e1),t5,-t5,t5,0.0,0.0,0.0,dt.*(-3.361344537815126e1),-t5,-t5,-t5,0.0,0.0,0.0,dt,dt,dt,dt,0.0,0.0,0.0,dt.*t2.*(-6.0e1./1.7e1),dt.*t2.*(-3.6e1./1.7e1),dt.*t2.*(3.6e1./1.7e1),dt.*t2.*(6.0e1./1.7e1),0.0,0.0,-t3],[7,5]);
