function h_x = measurement_function(in1,in2,in3,dt)
%MEASUREMENT_FUNCTION
%    H_X = MEASUREMENT_FUNCTION(IN1,IN2,IN3,DT)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    02-Aug-2019 13:28:46

b_p = in1(4,:);
b_q = in1(5,:);
p = in2(1,:);
q = in2(2,:);
r = in2(3,:);
theta_p = in1(1,:);
theta_1_prev = in3(1,:);
theta_2_prev = in3(2,:);
theta_3_prev = in3(3,:);
theta_4_prev = in3(4,:);
vx = in1(2,:);
vy = in1(3,:);
t2 = vx.*3.361344537815126e1;
t3 = vy.*3.361344537815126e1;
t4 = cos(theta_p);
t5 = sin(theta_p);
t6 = b_q-q;
t7 = r.*t4.*(3.6e1./1.7e1);
t8 = t5.*t6.*(6.0e1./1.7e1);
h_x = [theta_1_prev-dt.*(-b_p+p+t2+t3+t8-r.*t4.*(6.0e1./1.7e1));theta_2_prev+dt.*(b_p-p+t2-t3+t7-t5.*t6.*(3.6e1./1.7e1));theta_3_prev-dt.*(-b_p+p+t2+t3+t7-t5.*t6.*(3.6e1./1.7e1));theta_4_prev+dt.*(b_p-p+t2-t3+t8-r.*t4.*(6.0e1./1.7e1));t5;t4;-r.*t5-t4.*t6];
