function f_x_u = state_transition_function(in1,in2,dt)
%STATE_TRANSITION_FUNCTION
%    F_X_U = STATE_TRANSITION_FUNCTION(IN1,IN2,DT)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    02-Aug-2019 13:28:46

b_p = in1(4,:);
b_q = in1(5,:);
p = in2(1,:);
theta_p = in1(1,:);
vx = in1(2,:);
vy = in1(3,:);
f_x_u = [theta_p-dt.*(b_p-p);vx;vy;b_p;b_q];
