function F_x_u = state_transition_jacobian_function(in1,in2,dt)
%STATE_TRANSITION_JACOBIAN_FUNCTION
%    F_X_U = STATE_TRANSITION_JACOBIAN_FUNCTION(IN1,IN2,DT)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    02-Aug-2019 13:28:46

F_x_u = reshape([1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-dt,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0],[5,5]);
