/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * uFB.c
 *
 * Code generation for function 'uFB'
 *
 */

/* Include files */
#include "uFB.h"
#include "mwmathutil.h"
#include "rt_nonfinite.h"

/* Function Definitions */
void uFB(const emlrtStack *sp, const real_T in1[8], const real_T in2[3], real_T
         v[3])
{
  real_T t2;
  real_T t3;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t42_tmp;
  real_T t44_tmp;
  real_T t44;
  real_T t48_tmp;
  real_T b_t48_tmp;
  real_T t48;
  real_T t54_tmp;
  real_T t54;
  real_T v_tmp;
  (void)sp;

  /* UFB */
  /*     V = UFB(IN1,IN2) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
  /*     07-Jun-2020 14:24:01 */
  t2 = muDoubleScalarCos(in1[3]);
  t3 = muDoubleScalarSin(in1[3]);
  t5 = in1[6] * in1[6];
  t6 = t2 * t2;
  t7 = muDoubleScalarSin(in1[3] * 2.0);
  t8 = t3 * t3;
  t42_tmp = t3 * t6;
  t44_tmp = t6 * t8;
  t44 = 1.0 / (((((t3 * 1.6624316354668391E-14 - t42_tmp *
                   4.8224626801869287E-15) + -(t6 * 2.554188920360585E-13)) + t8
                 * 8.0736743342654317E-13) + -(t44_tmp * 2.342050785026386E-13))
               + 8.8049711231808578E-13);
  t48_tmp = t2 * t3;
  b_t48_tmp = t2 * t8;
  t48 = 1.0 / (t2 * 0.0001994930875 + 9.08773621875E-5) * (t6 * 4.49657419225E-5
    - 0.0001550089173138068) * (((t3 * 1.0724748384E-10 + t8 *
    5.20852249933514E-9) + 5.6802997374374863E-9) * t44 * 4.4911946750946972E-5
    + ((t48_tmp * 2.1395131677847961E-14 + t2 * 1.133180532546843E-12) +
       b_t48_tmp * 1.039064234705584E-12) * t44 * 0.02975) * in1[7];
  t54_tmp = t48 - in1[5];
  t54 = ((t2 * in1[6] * in1[7] * 0.4508 + -(in1[6] * 0.020908353929807218)) +
         in1[4] * 6.4937496736386819) + in1[6] * t54_tmp * 3.22;
  v_tmp = (((t6 * 1.2086791428768E-11 + t3 * 1.9327004690602211E-9) + -(t42_tmp *
             5.6064716799048188E-10)) - 4.1666396973951272E-11) * t44;
  t42_tmp = ((t7 * in1[6] * in1[7] * 0.045544378787878793 + in1[6] *
              0.0074642823529411763) - in1[4] * 0.072758621309486363) + t3 *
    in1[6] * t54_tmp * 0.2254;
  v[0] = (in2[0] - t44 * t54 * (((t6 * 8.3632032726157855E-11 - t8 *
             3.9052192655896047E-10) + t44_tmp * 1.132845030404171E-10) -
           2.8830194480006559E-10) * 0.0008850625) - v_tmp * t42_tmp *
    0.0008850625;
  v[1] = (in2[1] - v_tmp * t54 * 0.0008850625) - t44 * (t6 *
    8.5848067536148844E-9 - 2.959412084247702E-8) * t42_tmp * 0.0008850625;
  v[2] = (in2[2] - t44 * ((t3 * 3.2760902294540281E-13 + t8 *
            1.5910480189372179E-11) + 1.735161870832496E-11) * (((((t3 *
    2.211174 + t48 * 0.003132773109243698) - in1[5] * 0.003132773109243698) -
             in1[7] * 9.32E-5) + t5 * t7 * 0.02277218939393939) + t2 * in1[4] *
           in1[6] * 0.2254)) + t44 * ((t2 * 1.280339560818409E-9 + t48_tmp *
    2.4173582857536E-11) + b_t48_tmp * 1.174000971350141E-9) * (((((t48 *
    -0.99563590141939118 + in1[5] * 0.99563590141939118) + in1[7] *
    0.003132773109243698) + t3 * t5 * 0.2254) + in1[4] * in1[6] * 3.22) + t3 *
    (in1[7] * in1[7]) * 0.2254) * 0.0008850625;
}

/* End of code generation (uFB.c) */
