function [ MPC ] = get_simulation_controller( modelData )
%GET_SIMULATION_CONTROLLER Summary of this function goes here
%   Detailed explanation goes here

MPC = Derive_MPC_Reference_Previewing(modelData ...
    , 'Ts', 0.035 ... Increasing this allows greater access to the constrained set for an equivalent nc
    , 'nc', 10 ...
    , 'nr', 10 ...  Surprisingly nr>nc gives good results on figure 8 simulation
    , 'Q', diag([1 1 1 0 0 0 0 1E-2]) ...
    , 'R', 0.2*eye(4) ... 
    , 'umax', 0.1*ones(4,1) ... 
    , 'theta_p_max', 0.3 ...
    , 'v_y_max', 1 ...
    , 'v_x_max', 1 ...
    , 'phi_dot_max', 4 ...
    , 'MAS', 'minimal' ...
    , 'MAS_tolerance', 1E-9 ... % 3E-3 seems to cause instability, 1E-3 seems ok
    , 'removeConstraints', 1 ...
    , 'slackType', 'individualToNiForThetaPAndVyThenShared' ... % Managed 1000 feasible with individualToNiThenShared with ni=2
    ..., 'slackType', 'individualToNiThenShared' ... % Managed 1000 feasible with individualToNiThenShared with ni=2
    ..., 'slackType', 'individual' ...
    , 'ni', 3 ... 3 appears to be optimal for smooth transitions between constrained and unconstrained regions
    , 'cinf_weighting', 1E-12 ... Don't take below 1E-13 or weird stuff starts happening
    , 's_weight', [1E4 1E-5 1E-5 1E-5] ...
    , 's_weight_inf' , [1E5 1E5 1E2 1E2] ... % 1E3 for theta_p gives willingful violation, 1E4 gives a small overshoot on theta_p, 1E5 gives tight constraint tracking
    , 'generateCode', false ...
    , 'verbosity', 2 ...
    , 'forceRegen', false ...
    );

end

