

%% Requires three results, res_lin_ni1 through res_lin_ni3.

numSteps = size(res_lin_ni1.x,2);
T = 0:res_lin_ni1.MPC.Ts:res_lin_ni1.MPC.Ts*(numSteps-1);
y_lim_scale = 1.3;

thetap = [res_lin_ni1.x(4,:)' res_lin_ni2.x(4,:)' res_lin_ni3.x(4,:)'];
vy = [res_lin_ni1.x(6,:)' res_lin_ni2.x(6,:)' res_lin_ni3.x(6,:)'];

figure('Position', [680 433 560 545]);
subplot(2,1,1);
plot(T,thetap);
hold on;
plot([T(1),T(end); T(1),T(end)]',[res_lin_ni1.MPC.theta_p_max,res_lin_ni1.MPC.theta_p_max; -res_lin_ni1.MPC.theta_p_max,-res_lin_ni1.MPC.theta_p_max]', '-.','Color',	[0.8500, 0.3250, 0.0980]);
ylim(max([max(abs(thetap)) res_lin_ni1.MPC.theta_p_max])*[-y_lim_scale y_lim_scale]);
ylabel('$\theta_p \ (\unit{rad})$');
legend({'\(n_i=1\)','\(n_i=2\)','\(n_i=3\)'})

subplot(2,1,2);
plot(T,vy);
hold on;
ylabel('\(\dot{y} \ (\unit{ms^{-1}})\)');
plot([T(1),T(end); T(1),T(end)]',[res_lin_ni1.MPC.v_y_max,res_lin_ni1.MPC.v_y_max; -res_lin_ni1.MPC.v_y_max,-res_lin_ni1.MPC.v_y_max]', '-.','Color',	[0.8500, 0.3250, 0.0980]);

% matlab2tikz('D:\Google_Drive\Matlab\Matt_MPC\Figures\ni_constraint_violation_comparison.tex' ...
%     , 'width', '0.65\linewidth' ...
%     , 'parseStrings', false ...
%     , 'extraaxisoptions',[ ...
%     'title style={font=\footnotesize},'...
%     'xlabel style={font=\footnotesize},'...
%     'ylabel near ticks,'... 'every axis y label/.style={font=\footnotesize,at={(ticklabel cs:0.5,0.3)},rotate=90,anchor=center},'  ...
%     'ticklabel style={font=\scriptsize},' ...
%     'legend style={font=\scriptsize},'...,at={(1.45,1)},anchor=north east},' ...
%     'legend pos=outer north east,' ...
%     ... 'height=0.3\linewidth,'...
%     ...' scaled y ticks = false,' ...
%     ...' y tick label style={/pgf/number format/fixed},' ...
%     ]);