/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * Pz_v_to_u.c
 *
 * Code generation for function 'Pz_v_to_u'
 *
 */

/* Include files */
#include "Pz_v_to_u.h"
#include "mwmathutil.h"
#include "rt_nonfinite.h"

/* Function Definitions */
void Pz_v_to_u(const emlrtStack *sp, const real_T in1[8], const real_T in2[3],
               real_T u[3])
{
  real_T t2;
  real_T t3;
  real_T t4;
  (void)sp;

  /* PZ_V_TO_U */
  /*     U = PZ_V_TO_U(IN1,IN2) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
  /*     07-Jun-2020 14:24:03 */
  t2 = muDoubleScalarCos(in1[3]);
  t3 = muDoubleScalarSin(in1[3]);
  t4 = t3 * 0.2254;
  u[0] = in2[0] * 3.451396087846903 + (t4 - 0.004859317844784973) * in2[1];
  u[1] = in2[2] * (t2 * t2 * 1.13056722548E+11 - 3.89736706389E+11) *
    -1.06951871657754E-5 / (t2 * 5.36452E+6 + 2.443761E+6);
  u[2] = (t4 - 0.004859317844784973) * in2[0] + in2[1] * (t3 * t3 *
    0.045544378787878793 + 0.033623036470588237);
}

/* End of code generation (Pz_v_to_u.c) */
