/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * f_solve_fdvy_theta_p_x.c
 *
 * Code generation for function 'f_solve_fdvy_theta_p_x'
 *
 */

/* Include files */
#include "f_solve_fdvy_theta_p_x.h"
#include "mwmathutil.h"
#include "rt_nonfinite.h"

/* Function Definitions */
void f_solve_fdvy_theta_p_x(const emlrtStack *sp, const real_T in1[8], const
  real_T in2[3], real_T dvy, real_T *fun, real_T *dFun)
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t8;
  real_T t9;
  real_T t11;
  real_T t12;
  real_T t26;
  real_T t27;
  real_T t74_tmp;
  real_T t74;
  real_T t85;
  real_T t75;
  real_T t41;
  real_T t48;
  real_T t76;
  real_T t77;
  real_T t78;
  real_T t79;
  real_T t80;
  real_T t81_tmp;
  real_T t81;
  real_T t97_tmp;
  real_T b_t97_tmp;
  real_T t97;
  real_T fun_tmp_tmp;
  real_T fun_tmp;
  real_T b_fun_tmp;
  real_T t98;
  real_T dFun_tmp;
  (void)sp;

  /* F_SOLVE_FDVY_THETA_P_X */
  /*     [FUN,DFUN] = F_SOLVE_FDVY_THETA_P_X(IN1,IN2,DVY) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
  /*     07-Jun-2020 14:22:11 */
  t2 = muDoubleScalarCos(in1[3]);
  t3 = muDoubleScalarSin(in1[3]);
  t4 = in1[3] * 2.0;
  t5 = in1[6] * in1[6];
  t6 = in1[7] * in1[7];
  t8 = t2 * t2;
  t9 = muDoubleScalarPower(t2, 3.0);
  t11 = t3 * t3;
  t12 = muDoubleScalarPower(t3, 3.0);
  t26 = t2 * t5 * 0.2254 + t2 * t6 * 0.2254;
  t27 = t8 * 4.49657419225E-5;
  t74_tmp = t2 * t3;
  t74 = t2 * 1.0724748384E-10 + t74_tmp * 1.041704499867028E-8;
  t85 = in1[4] * in1[6];
  t75 = (((t85 * 3.22 + t3 * t5 * 0.2254) + t3 * t6 * 0.2254) + in1[7] *
         0.003132773109243698) + in1[5] * 0.99563590141939118;
  t41 = 1.0 / (t2 * 0.0001994930875 + 9.08773621875E-5);
  t48 = (-(t85 * t3 * 0.2254) + t2 * 2.211174) + t5 * muDoubleScalarCos(t4) *
    0.045544378787878793;
  t76 = (t3 * 1.0724748384E-10 + t11 * 5.20852249933514E-9) +
    5.6802997374374863E-9;
  t77 = (((t85 * t2 * 0.2254 + t3 * 2.211174) + t5 * muDoubleScalarSin(t4) *
          0.02277218939393939) + -(in1[7] * 9.32E-5)) + -(in1[5] *
    0.003132773109243698);
  t6 = t2 * t11;
  t78 = (t74_tmp * 2.4173582857536E-11 + t2 * 1.280339560818409E-9) + t6 *
    1.174000971350141E-9;
  t79 = (t3 * 3.2760902294540281E-13 + t11 * 1.5910480189372179E-11) +
    1.735161870832496E-11;
  t80 = (t74_tmp * 2.1395131677847961E-14 + t2 * 1.133180532546843E-12) + t6 *
    1.039064234705584E-12;
  t81_tmp = t3 * t8;
  t81 = (((t11 * 2.1395131677847961E-14 + -(t8 * 2.1395131677847961E-14)) + t12 *
          1.039064234705584E-12) + t3 * 1.133180532546843E-12) + -(t81_tmp *
    2.078128469411168E-12);
  t4 = ((((t6 * 9.6449253603738589E-15 + -(t9 * 4.8224626801869287E-15)) + t2 *
          1.6624316354668391E-14) + t2 * t12 * 4.684101570052772E-13) + -(t3 *
         t9 * 4.684101570052772E-13)) + t74_tmp * 2.1255726509252028E-12;
  t5 = 1.0 / (((((t3 * 1.6624316354668391E-14 - t81_tmp * 4.8224626801869287E-15)
                 + -(t8 * 2.554188920360585E-13)) + t11 * 8.0736743342654317E-13)
               + -(t8 * t11 * 2.342050785026386E-13)) + 8.8049711231808578E-13);
  t85 = t5 * t5;
  t9 = t76 * t4 * t85 * 4.4911946750946972E-5;
  t6 = t76 * t5 * 4.4911946750946972E-5 + t80 * t5 * 0.02975;
  t97_tmp = t75 * t78;
  b_t97_tmp = t77 * t79;
  t97 = t97_tmp * t5 * 0.0008850625 + -(b_t97_tmp * t5);
  fun_tmp_tmp = t41 * (t27 - 0.0001550089173138068);
  fun_tmp = fun_tmp_tmp * t6;
  b_fun_tmp = t77 * t80;
  *fun = (((-dvy - t75 * t76 * t5 * 4.4911946750946972E-5) + b_fun_tmp * t5) -
          fun_tmp * t97) - fun_tmp * in2[2];
  t98 = ((-(t74 * t5 * 4.4911946750946972E-5) + t81 * t5 * 0.02975) + t9) + t80 *
    t4 * t85 * 0.02975;
  dFun_tmp = t74_tmp * t41 * t6;
  t6 *= t3 * (t41 * t41) * (t27 - 0.0001550089173138068);
  *dFun = (((((((((((t75 * t9 - t26 * t76 * t5 * 4.4911946750946972E-5) + t48 *
                    t80 * t5) - t74 * t75 * t5 * 4.4911946750946972E-5) - t77 *
                  t81 * t5) + fun_tmp_tmp * t97 * t98) - b_fun_tmp * t4 * t85) +
               fun_tmp_tmp * t98 * in2[2]) + fun_tmp * (((((t75 * t5 * ((((t3 *
    1.280339560818409E-9 - t8 * 2.4173582857536E-11) + t11 * 2.4173582857536E-11)
    + t12 * 1.174000971350141E-9) - t81_tmp * 2.3480019427002812E-9) *
    0.0008850625 - t26 * t78 * t5 * 0.0008850625) + t48 * t79 * t5) + t77 * t5 *
    (t2 * 3.2760902294540281E-13 + t74_tmp * 3.1820960378744352E-11)) + t97_tmp *
    t4 * t85 * 0.0008850625) - b_t97_tmp * t4 * t85)) + dFun_tmp * t97 *
             8.9931483845E-5) - t6 * t97 * 0.0001994930875) + dFun_tmp * in2[2] *
           8.9931483845E-5) - t6 * in2[2] * 0.0001994930875;
}

/* End of code generation (f_solve_fdvy_theta_p_x.c) */
