/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * dvy_ss_fun.c
 *
 * Code generation for function 'dvy_ss_fun'
 *
 */

/* Include files */
#include "dvy_ss_fun.h"
#include "mwmathutil.h"
#include "rt_nonfinite.h"

/* Function Definitions */
real_T dvy_ss_fun(const emlrtStack *sp, const real_T in1[8], const real_T in2[3])
{
  real_T t2;
  real_T t3;
  real_T t5;
  real_T t6;
  real_T t8;
  real_T t32;
  real_T t25;
  real_T t33_tmp;
  real_T b_t33_tmp;
  real_T t33;
  real_T t35;
  (void)sp;
  (void)in2;

  /* DVY_SS_FUN */
  /*     DVY_SS = DVY_SS_FUN(IN1,IN2) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
  /*     07-Jun-2020 14:22:14 */
  t2 = muDoubleScalarCos(in1[3]);
  t3 = muDoubleScalarSin(in1[3]);
  t5 = in1[6] * in1[6];
  t6 = t2 * t2;
  t8 = t3 * t3;
  t32 = in1[4] * in1[6];
  t25 = (t32 * 3.22 + t3 * t5 * 0.2254) + in1[5] * 0.99563590141939118;
  t5 = ((t32 * t2 * 0.2254 + t3 * 2.211174) + t5 * muDoubleScalarSin(in1[3] *
         2.0) * 0.02277218939393939) + -(in1[5] * 0.003132773109243698);
  t32 = (t3 * 1.0724748384E-10 + t8 * 5.20852249933514E-9) +
    5.6802997374374863E-9;
  t33_tmp = t2 * t3;
  b_t33_tmp = t2 * t8;
  t33 = (t33_tmp * 2.1395131677847961E-14 + t2 * 1.133180532546843E-12) +
    b_t33_tmp * 1.039064234705584E-12;
  t35 = 1.0 / (((((t3 * 1.6624316354668391E-14 - t3 * t6 *
                   4.8224626801869287E-15) + -(t6 * 2.554188920360585E-13)) + t8
                 * 8.0736743342654317E-13) + -(t6 * t8 * 2.342050785026386E-13))
               + 8.8049711231808578E-13);
  return (t25 * t32 * t35 * -4.4911946750946972E-5 + t5 * t33 * t35) - (t32 *
    t35 * 4.4911946750946972E-5 + t33 * t35 * 0.02975) * (t6 * 4.49657419225E-5
    - 0.0001550089173138068) * (t25 * t35 * ((t2 * 1.280339560818409E-9 +
    t33_tmp * 2.4173582857536E-11) + b_t33_tmp * 1.174000971350141E-9) *
    0.0008850625 - t5 * t35 * ((t3 * 3.2760902294540281E-13 + t8 *
    1.5910480189372179E-11) + 1.735161870832496E-11)) / (t2 * 0.0001994930875 +
    9.08773621875E-5);
}

/* End of code generation (dvy_ss_fun.c) */
