function [dxp,dyp,vxp,vyp,dvxp,dvyp,ddvxp,ddvyp] = calculateInertialVelocityPerturbations(dxr,dyr,phir,dphir)
%CALCULATEINERTIALVELOCITYPERTURBATIONS
%    [DXP,DYP,VXP,VYP,DVXP,DVYP,DDVXP,DDVYP] = CALCULATEINERTIALVELOCITYPERTURBATIONS(DXR,DYR,PHIR,DPHIR)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    07-Jun-2020 14:25:40

t2 = cos(phir);
t3 = sin(phir);
t4 = dphir.^2;
t5 = dphir.^3;
t6 = phir.*2.0;
t7 = cos(t6);
t8 = sin(t6);
t9 = t4.*5.14642399976e+11;
t10 = t9-2.84880220876251e+14;
t11 = 1.0./t10;
dxp = t11.*(dxr.*-2.84880220876251e+14+dxr.*t9+dphir.*dxr.*t8.*5.9757221944e+11-dphir.*dyr.*t7.*5.9757221944e+11+dxr.*t4.*t7.*1.55308109824e+11+dyr.*t4.*t8.*1.55308109824e+11);
if nargout > 1
    dyp = -t11.*(dyr.*2.84880220876251e+14-dyr.*t4.*5.14642399976e+11+dphir.*dxr.*t7.*5.9757221944e+11+dphir.*dyr.*t8.*5.9757221944e+11-dxr.*t4.*t8.*1.55308109824e+11+dyr.*t4.*t7.*1.55308109824e+11);
end
if nargout > 2
    vxp = dxr.*t2.*1.301778691050801+dyr.*t3.*1.301778691050801+t11.*(dphir.*(dxr.*t3.*5.9757221944e+11-dyr.*t2.*5.9757221944e+11)+dxr.*t2.*8.597078016229807e+13+dyr.*t3.*8.597078016229807e+13);
end
if nargout > 3
    vyp = dxr.*t3.*(-6.982213089491991e-1)+dyr.*t2.*6.982213089491991e-1-t11.*(dphir.*(dxr.*t2.*5.9757221944e+11+dyr.*t3.*5.9757221944e+11)-dxr.*t3.*8.597078016229807e+13+dyr.*t2.*8.597078016229807e+13);
end
if nargout > 4
    dvxp = t11.*(dphir.*dxr.*t3.*2.84880220876251e+14-dphir.*dyr.*t2.*2.84880220876251e+14+dxr.*t2.*t4.*5.9757221944e+11-dxr.*t3.*t5.*6.699505098e+11+dyr.*t2.*t5.*6.699505098e+11+dyr.*t3.*t4.*5.9757221944e+11);
end
if nargout > 5
    dvyp = t11.*(dphir.*dxr.*t2.*2.84880220876251e+14+dphir.*dyr.*t3.*2.84880220876251e+14-dxr.*t2.*t5.*3.59334290152e+11+dxr.*t3.*t4.*5.9757221944e+11-dyr.*t2.*t4.*5.9757221944e+11-dyr.*t3.*t5.*3.59334290152e+11);
end
if nargout > 6
    ddvxp = t4.*t11.*(dxr.*t2.*2.84880220876251e+14+dyr.*t3.*2.84880220876251e+14-dphir.*dxr.*t3.*5.9757221944e+11+dphir.*dyr.*t2.*5.9757221944e+11-dxr.*t2.*t4.*6.699505098e+11-dyr.*t3.*t4.*6.699505098e+11);
end
if nargout > 7
    ddvyp = t4.*t11.*(dxr.*t3.*-2.84880220876251e+14+dyr.*t2.*2.84880220876251e+14+dphir.*dxr.*t2.*5.9757221944e+11+dphir.*dyr.*t3.*5.9757221944e+11+dxr.*t3.*t4.*3.59334290152e+11-dyr.*t2.*t4.*3.59334290152e+11);
end
