function out1 = TVLQR_e_fun(in1,in2,in3)
%TVLQR_E_FUN
%    OUT1 = TVLQR_E_FUN(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    07-Jun-2020 14:21:25

e_phi_int = in3(3,:);
e_x_int = in3(1,:);
e_y_int = in3(2,:);
state1 = in1(1,:);
state2 = in1(2,:);
state3 = in1(3,:);
state4 = in1(4,:);
state5 = in1(5,:);
state6 = in1(6,:);
state7 = in1(7,:);
state8 = in1(8,:);
xr_1 = in2(1,:);
xr_2 = in2(2,:);
xr_3 = in2(3,:);
xr_4 = in2(4,:);
xr_5 = in2(5,:);
xr_6 = in2(6,:);
xr_7 = in2(7,:);
xr_8 = in2(8,:);
t2 = cos(state3);
t3 = sin(state3);
t4 = -xr_1;
t5 = -xr_2;
t6 = state1+t4;
t7 = state2+t5;
out1 = [e_x_int.*t2+e_y_int.*t3;-e_x_int.*t3+e_y_int.*t2;e_phi_int;-t2.*t6-t3.*t7;-t2.*t7+t3.*t6;-state3+xr_3;-state4+xr_4;-state5+xr_5;-state6+xr_6;-state7+xr_7;-state8+xr_8];
