function [  ] = matlab2Tikz2ColumnWrapper( path )
%MATLAB2TIKZZWRAPPER Summary of this function goes here
%   Detailed explanation goes here
cleanfigure

%   matlab2tikz(path, 'width', '0.9\linewidth', 'parseStrings', false, ...
%         'extraaxisoptions',['title style={font=\footnotesize},'...
%         'title style={yshift=-1.5ex},' ...
%         'every axis plot/.append style={thin},' ...
%         'xlabel style={font=\footnotesize},'...
%         'ylabel style={font=\footnotesize},' ...
%         'ticklabel style={font=\scriptsize},' ...
%         'height=0.2\linewidth,'...
%         ' scaled y ticks = true,' ...
%         ...' y tick label style={/pgf/number format/fixed},' ...
%         ]);
    
  matlab2tikz(path, 'width', '0.9\linewidth', 'parseStrings', false]);
end

