/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * inertial_vel_control_dw1_dw2_dtheta_pr_fun.c
 *
 * Code generation for function 'inertial_vel_control_dw1_dw2_dtheta_pr_fun'
 *
 */

/* Include files */
#include "inertial_vel_control_dw1_dw2_dtheta_pr_fun.h"
#include "mwmathutil.h"
#include "rt_nonfinite.h"

/* Function Definitions */
void inertial_vel_control_dw1_dw2_dtheta_pr_fun(const emlrtStack *sp, const
  real_T in1[8], const real_T in2[3], real_T Kv, real_T Kdphi, real_T Kr, real_T
  Kw1, real_T Kw2, real_T theta_p_max, real_T w1_max, real_T w2_max, real_T
  theta_pr, real_T dxr, real_T dyr, real_T dphir, real_T fss_minus1_dvy_mvxdphi,
  real_T K_slow_dtheta_p, real_T K_slow_theta_p, real_T *dtheta_pr, real_T *dw1,
  real_T *dw2)
{
  real_T t2;
  real_T t3;
  real_T t4;
  real_T t5;
  real_T t6;
  real_T t7;
  real_T t8;
  real_T t9;
  real_T t11;
  real_T t12;
  real_T t13;
  real_T t14;
  real_T t16;
  real_T t19;
  real_T t35_tmp;
  real_T t35;
  real_T t49;
  real_T t51;
  real_T t20;
  real_T t21;
  real_T t22;
  real_T t23;
  real_T t24;
  real_T t25;
  real_T t27;
  real_T t29;
  real_T t33;
  real_T t34;
  real_T t36;
  real_T t37;
  real_T t66;
  real_T t67;
  real_T t38;
  real_T t78;
  real_T t80;
  real_T t82_tmp;
  real_T b_t82_tmp;
  real_T t82;
  real_T t86;
  real_T t87;
  real_T dtheta_pr_tmp;
  real_T b_dtheta_pr_tmp;
  (void)sp;

  /* INERTIAL_VEL_CONTROL_DW1_DW2_DTHETA_PR_FUN */
  /*     [DTHETA_PR,DW1,DW2] = INERTIAL_VEL_CONTROL_DW1_DW2_DTHETA_PR_FUN(IN1,IN2,KV,KDPHI,KR,KW1,KW2,THETA_P_MAX,W1_MAX,W2_MAX,THETA_PR,DXR,DYR,DPHIR,FSS_MINUS1_DVY_MVXDPHI,K_SLOW_DTHETA_P,K_SLOW_THETA_P) */
  /*     This function was generated by the Symbolic Math Toolbox version 8.4. */
  /*     27-Jan-2020 10:02:33 */
  t2 = muDoubleScalarCos(fss_minus1_dvy_mvxdphi);
  t3 = muDoubleScalarCos(in1[2]);
  t4 = muDoubleScalarCos(in1[3]);
  t5 = muDoubleScalarCos(theta_pr);
  t6 = muDoubleScalarSin(fss_minus1_dvy_mvxdphi);
  t7 = muDoubleScalarSin(in1[2]);
  t8 = muDoubleScalarSin(in1[3]);
  t9 = muDoubleScalarSin(theta_pr);
  t11 = in1[5] * in1[6];
  t12 = in1[4] * in2[1];
  t13 = in1[6] * in2[0];
  t14 = fss_minus1_dvy_mvxdphi * 2.0;
  t16 = in1[6] * in1[6];
  t19 = theta_p_max * theta_p_max;
  t35_tmp = in1[4] * in1[6];
  t35 = t35_tmp * 3.22;
  t49 = in1[5] * 0.003132773109243698;
  t51 = in1[5] * 0.99563590141939118;
  t20 = muDoubleScalarCos(t14);
  t21 = t2 * t2;
  t22 = t4 * t4;
  t23 = t5 * t5;
  t24 = muDoubleScalarSin(t14);
  t25 = t6 * t6;
  t27 = t8 * t8;
  t29 = t9 * t9;
  t33 = fss_minus1_dvy_mvxdphi + -theta_pr;
  t34 = t12 + t13;
  t36 = theta_pr * theta_pr + -t19;
  t37 = fss_minus1_dvy_mvxdphi * theta_pr + -t19;
  t66 = (t35 + t8 * t16 * 0.2254) + t51;
  t67 = (t35 + t9 * t16 * 0.2254) + t51;
  t38 = 1.0 / t37;
  t78 = ((t35_tmp * t4 * 0.2254 + t8 * 2.211174) + t16 * muDoubleScalarSin(in1[3]
          * 2.0) * 0.02277218939393939) + -t49;
  t14 = ((t35_tmp * t5 * 0.2254 + t9 * 2.211174) + t16 * muDoubleScalarSin
         (theta_pr * 2.0) * 0.02277218939393939) + -t49;
  t80 = (t8 * 1.0724748384E-10 + t27 * 5.20852249933514E-9) +
    5.6802997374374863E-9;
  t19 = (t9 * 1.0724748384E-10 + t29 * 5.20852249933514E-9) +
    5.6802997374374863E-9;
  t82_tmp = t4 * t8;
  b_t82_tmp = t4 * t27;
  t82 = (t82_tmp * 2.1395131677847961E-14 + t4 * 1.133180532546843E-12) +
    b_t82_tmp * 1.039064234705584E-12;
  t35 = t5 * t9;
  t51 = t5 * t29;
  t49 = (t35 * 2.1395131677847961E-14 + t5 * 1.133180532546843E-12) + t51 *
    1.039064234705584E-12;
  t86 = 1.0 / (((((t8 * 1.6624316354668391E-14 - t8 * t22 *
                   4.8224626801869287E-15) + -(t22 * 2.554188920360585E-13)) +
                 t27 * 8.0736743342654317E-13) + -(t22 * t27 *
    2.342050785026386E-13)) + 8.8049711231808578E-13);
  t87 = 1.0 / (((((t9 * 1.6624316354668391E-14 - t9 * t23 *
                   4.8224626801869287E-15) + -(t23 * 2.554188920360585E-13)) +
                 t29 * 8.0736743342654317E-13) + -(t23 * t29 *
    2.342050785026386E-13)) + 8.8049711231808578E-13);
  dtheta_pr_tmp = in1[6] * t2;
  b_dtheta_pr_tmp = t2 * t16;
  *dtheta_pr = muDoubleScalarExp(-K_slow_theta_p * muDoubleScalarAbs(in1[3] +
    -theta_pr) - K_slow_dtheta_p * muDoubleScalarAbs(in1[7])) * (Kr * t33 * t37
    - Kv * (t36 * t36) * t38 * ((in1[5] + dxr * t7) - dyr * t3) * (((t35_tmp -
    t67 * t19 * t87 * 4.4911946750946972E-5) + t14 * t49 * t87) - (t19 * t87 *
    4.4911946750946972E-5 + t49 * t87 * 0.02975) * (t23 * 4.49657419225E-5 -
    0.0001550089173138068) * (t67 * t87 * ((t5 * 1.280339560818409E-9 + t35 *
    2.4173582857536E-11) + t51 * 1.174000971350141E-9) * 0.0008850625 - t14 *
    t87 * ((t9 * 3.2760902294540281E-13 + t29 * 1.5910480189372179E-11) +
           1.735161870832496E-11)) / (t5 * 0.0001994930875 + 9.08773621875E-5)) /
    t33) - t36 * t38 * (((((((((((t12 * -1.4876213135623131E+30 - t13 *
    1.4876213135623131E+30) + t2 * t12 * 9.415106672479785E+31) + t2 * t13 *
    9.415106672479785E+31) + t12 * t21 * 1.0692406484316949E+32) + t13 * t21 *
    1.0692406484316949E+32) - t2 * t34 * 9.741667833290163E+31) - t21 * t34 *
    1.0692406484316949E+32) + in1[6] * t6 * in2[1] * 2.8981461804038229E+30) +
    in1[6] * t24 * in2[1] * 9.8420188514876134E+30) + dtheta_pr_tmp * t6 * in2[1]
    * 6.3619818581685849E+30) + dtheta_pr_tmp * t24 * in2[1] *
                        2.160510253219621E+31) / ((((((((((t2 *
    4.7782880722288249E+32 + t21 * 1.048925076111493E+33) + t25 *
    1.048925076111493E+33) + in1[5] * t6 * 1.256495091399306E+31) +
    b_dtheta_pr_tmp * 1.449073090201912E+30) + t16 * t20 *
    9.8420188514876134E+30) + t16 * t21 * 3.1809909290842919E+30) + t16 * t25 *
    3.1809909290842919E+30) - t35_tmp * t6 * 3.26561160810378E+30) +
    b_dtheta_pr_tmp * t20 * 2.160510253219621E+31) + t6 * t16 * t24 *
    1.08025512660981E+31);
  t19 = t11 - in2[0];
  t35 = t19 + w1_max;
  t14 = (-t11 + in2[0]) + w1_max;
  *dw1 = ((in1[5] * in2[1] + Kw1 * t19) - in1[6] * ((t66 * t80 * t86 *
            4.4911946750946972E-5 - t78 * t82 * t86) + (t80 * t86 *
            4.4911946750946972E-5 + t82 * t86 * 0.02975) * (t22 *
            4.49657419225E-5 - 0.0001550089173138068) * (t66 * t86 * ((t4 *
              1.280339560818409E-9 + t82_tmp * 2.4173582857536E-11) + b_t82_tmp *
             1.174000971350141E-9) * 0.0008850625 - t78 * t86 * ((t8 *
              3.2760902294540281E-13 + t27 * 1.5910480189372179E-11) +
             1.735161870832496E-11)) / (t4 * 0.0001994930875 + 9.08773621875E-5)))
    + Kv * (t35 * t35) * ((-in1[4] + dxr * t3) + dyr * t7) * (t14 * t14) /
    w1_max;
  t35 = in2[1] * in2[1] - w2_max * w2_max;
  *dw2 = -Kw2 * in2[1] + Kdphi * (t35 * t35) * (dphir - in1[6]);
}

/* End of code generation (inertial_vel_control_dw1_dw2_dtheta_pr_fun.c) */
